import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { RecHud } from "@/components/features/RecHud";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-mono")}
      style={{ fontFamily: "'Courier New', Courier, monospace" }}
    >
      <body className="min-h-full flex flex-col">
        {" "}
        <RecHud />
        {children}
      </body>
    </html>
  );
}
